version: "3"

services:
  app:
    build: .
    tty: true
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./app:/go/src/app
    environment:
      DB_HOSTNAME: mysql
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: db_22spring
    depends_on:
      - mysql
  
  mysql:
    build: ./mysql/
    platform: linux/x86_64
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db_22spring
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    container_name: mysql