version: "3"

services:
  app:
    build: .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/app
    depends_on:
      - mysql
  
  mysql:
    build: ./mysql/
    platform: linux/x86_64
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"
    container_name: mysql